import { IMPLEMENTATION_CHILDREN_PATH } from '../../constants';

export const TOURNAMENT_CHILDREN_PATH = {
  REGISTRATION: `${IMPLEMENTATION_CHILDREN_PATH.TOURNAMENT}`,
  GRID: `${IMPLEMENTATION_CHILDREN_PATH.TOURNAMENT}/grid`,
  LIST: `${IMPLEMENTATION_CHILDREN_PATH.TOURNAMENT}/list`,
  SEMI_FINAL: `${IMPLEMENTATION_CHILDREN_PATH.TOURNAMENT}/semi-final`,
  FINAL: `${IMPLEMENTATION_CHILDREN_PATH.TOURNAMENT}/final`,
  THIRD_PLACE: `${IMPLEMENTATION_CHILDREN_PATH.TOURNAMENT}/third-place`,
}