import { GAMES_CHILDREN_PATH } from '../../constants';

export const DRUNKARD_CHILDREN_PATH = {
  HOME: `${GAMES_CHILDREN_PATH.DRUNKARD}`,
  FC: `${GAMES_CHILDREN_PATH.DRUNKARD}/fc`,
  CL: `${GAMES_CHILDREN_PATH.DRUNKARD}/cl`,
};
