export const IMPLEMENTATION_PAGE_PATH = '/implementation';

export const IMPLEMENTATION_CHILDREN_PATH = {
  ATM: `${IMPLEMENTATION_PAGE_PATH}/atm`,
  BUTTONS: `${IMPLEMENTATION_PAGE_PATH}/buttons`,
  QUEUE: `${IMPLEMENTATION_PAGE_PATH}/queue`,
  TODO: `${IMPLEMENTATION_PAGE_PATH}/todo`,
  SNAKE: `${IMPLEMENTATION_PAGE_PATH}/snake`,
  SNAKE_REDUX: `${IMPLEMENTATION_PAGE_PATH}/snake-redux`,
  SNAKE_TOOLKIT: `${IMPLEMENTATION_PAGE_PATH}/snake-toolkit`,
};