export const IMPLEMENTATION_PAGE_PATH = '/implementation';

export const IMPLEMENTATION_CHILDREN_PATH = {
  ATM: `${IMPLEMENTATION_PAGE_PATH}/atm`,
  BUTTONS: `${IMPLEMENTATION_PAGE_PATH}/buttons`,
  QUEUE: `${IMPLEMENTATION_PAGE_PATH}/queue`,
  TODO: `${IMPLEMENTATION_PAGE_PATH}/todo`,
  SNAKE_GAME: `${IMPLEMENTATION_PAGE_PATH}/snake-game`,
  BAD_PRACTICES: `${IMPLEMENTATION_PAGE_PATH}/bad-practices`,
};